AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  MyBucket:
    Type: String
    Default: "erick-bucket-test"
    Description: Bucket name.
  MyRegion:
    Type: String
    Default: "us-east-1"
    Description: Region.
Resources:
  Bucket:
      Type: AWS::S3::Bucket
      Properties:
          AccessControl: Private
          BucketName: !Ref MyBucket
          PublicAccessBlockConfiguration:
            BlockPublicAcls: true
            BlockPublicPolicy: true
            IgnorePublicAcls: true
            RestrictPublicBuckets: true
          Tags:
              - Key: description
                Value: "Private files"
              - Key: region
                Value: !Ref "AWS::Region"
  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'origin identity'                  
  BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref MyBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
              Action: 's3:GetObject'
              Resource: !Sub arn:aws:s3:::${MyBucket}/*        
  publicDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${MyBucket}.s3.${MyRegion}.amazonaws.com
            Id: !Sub S3-${MyBucket}
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
        Enabled: true
        Comment: Some comment
        DefaultRootObject: "index.html"
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: !Sub S3-${MyBucket}
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: true